# Generated by Django 3.0.6 on 2020-08-03 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20200803_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
