# Generated by Django 3.0.6 on 2020-08-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_thread_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='recommendation',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
