# Generated by Django 3.0.6 on 2020-08-05 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20200805_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_comment_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='thread',
            name='last_comment_length',
            field=models.IntegerField(default=0),
        ),
    ]
