# Generated by Django 3.0.6 on 2020-08-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20200805_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='category',
            new_name='hamlet',
        ),
    ]
