# Generated by Django 3.0.6 on 2020-08-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20200806_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_receiver',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='chat_sender',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_group_name',
            field=models.CharField(default='', max_length=400),
        ),
    ]
