# Generated by Django 3.0.6 on 2020-08-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_auto_20200806_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_group_name',
        ),
    ]
