# Generated by Django 3.0.6 on 2020-08-06 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0016_remove_chat_chat_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='who_send',
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Chat')),
                ('who_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_send', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
