# Generated by Django 3.0.6 on 2020-08-07 14:15

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_auto_20200806_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('no_of_user', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='details',
            field=tinymce.models.HTMLField(),
        ),
    ]
