# Generated by Django 3.0.6 on 2020-08-08 14:00

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_auto_20200807_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrystats',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
