# Generated by Django 3.0.6 on 2020-08-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_auto_20200808_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
