# Generated by Django 3.0.6 on 2020-08-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_members_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
