# Generated by Django 3.0.6 on 2020-08-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_share_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='user',
            new_name='content_user',
        ),
        migrations.AddField(
            model_name='share',
            name='user_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
