# Generated by Django 3.0.6 on 2020-08-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_auto_20200814_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_of_creator',
            field=models.CharField(default='bode', max_length=500),
            preserve_default=False,
        ),
    ]
