# Generated by Django 3.0.6 on 2020-08-16 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0025_category_name_of_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='sharer_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='content_sharer_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='share',
            name='content_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_content_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
