# Generated by Django 3.0.6 on 2020-09-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0028_auto_20200824_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='recommendation',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=5000),
        ),
    ]
