# Generated by Django 3.0.6 on 2020-09-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0029_auto_20200917_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='timestamp',
            field=models.FloatField(default=1600441729.9177363),
        ),
    ]
