# Generated by Django 3.0.6 on 2020-08-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='graph',
            field=models.ImageField(blank=True, upload_to='poll_graph_result'),
        ),
        migrations.AddField(
            model_name='poll',
            name='graph_made',
            field=models.BooleanField(default=False),
        ),
    ]
