"""
Django settings for afrik project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import pymysql
pymysql.install_as_MySQLdb()

import os
import json

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '943f343e20d92fe33403bb53dd8139332ae87a525867d59b' 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
# DEBUG = True

ALLOWED_HOSTS = ['www.africonn.com', 'africonn.com']
# ALLOWED_HOSTS = ['*']

# Application definition


with open(os.path.join(BASE_DIR, "forum", "static", "config.json")) as config_file:
    config = json.load(config_file)

INSTALLED_APPS = [
    # my apps
    'forum',
    'job',
    'root.apps.RootConfig',
    'polls',
    'blog',
    
    #django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    # 3rd party apps
    'mathfilters',
    'crispy_forms',
    'django_social_share',
    'tinymce',
    'django_countries',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'afrik.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'forum.context_precessors.home'
            ],
        },
    },
]

WSGI_APPLICATION = 'afrik.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',   
#         "NAME": "african",
#         "HOST": "localhost",
#         "PASSWORD": "azeez007",
#         "USER": "root",
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',   
        "NAME": "africonn",
        "HOST": "dataslid.c0wfhbraw7u6.us-east-1.rds.amazonaws.com",
        "USER": "dataslid",
        "PASSWORD": config.get("DB_PASSWORD"),
        "PORT": "3306",
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    }
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# GEOIP
GEOIP_PATH = os.path.join(BASE_DIR, "forum", "static", "geo_db")
GEOIP_CITY = 'GeoLite2-City.mmdb'
GEOIP_COUNTRY = 'GeoLite2-Country.mmdb'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
LOGIN_REDIRECT_URL = "followers-content/"
LOGOUT_REDIRECT_URL = "login"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = '/media/'
CRISPY_TEMPLATE_PACK = "bootstrap4"

# SES
EMAIL_BACKEND = 'django_ses.SESBackend'
DEFAULT_FROM_EMAIL = config.get("EMAIL")
AWS_ACCESS_KEY_ID = config.get("AWS_S3_ACCESS_KEYID")

X_FRAME_OPTIONS = 'SAMEORIGIN'

AWS_SECRET_ACCESS_KEY = config.get("AWS_SECRET_ACCESS_KEY")
AWS_S3_ACCESS_KEY_ID = "AKIA5NZ7IZHALP2IU3MI"#
AWS_STORAGE_BUCKET_NAME = config.get("AWS_STORAGE_BUCKET_NAME")

AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

AWS_S3_REGION_NAME = "us-east-2"
AWS_S3_SIGNATURE_VERSION = "s3v4"

TINYMCE_DEFAULT_CONFIG = {
    'selector': 'textarea',
    'theme': 'modern',
    'plugins': 'emoticons table code table',
    'toolbar1': 'bold italic underline | alignleft aligncenter alignright alignjustify emoticons '
               '| bullist numlist | outdent indent | table ',
    'menubar': False,
    'inline': False,
    'statusbar': True,
    'height': 200,
    'default_link_target': "_blank"
}