# Generated by Django 3.0.6 on 2020-08-08 21:05

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='ad_country',
            field=django_countries.fields.CountryField(default='NG', max_length=2),
            preserve_default=False,
        ),
    ]
