# Generated by Django 3.0.6 on 2020-08-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_advert_ad_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='cost',
            field=models.FloatField(),
        ),
    ]
