# Generated by Django 3.0.6 on 2020-09-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_advert_advert_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
    ]
